services:
  db:
    image: mariadb:lts
    container_name: scheduler_mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: spark
      MARIADB_DATABASE: schedulerDB
      MARIADB_USER: devuser
      MARIADB_PASSWORD: devpassword
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./seed.sql:/docker-entrypoint-initdb.d/1-seed.sql:ro

volumes:
  mariadb_data:
