/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResultsHashRouteImport } from './routes/results/$hash'
import { Route as AvailabilityHashRouteImport } from './routes/availability/$hash'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsHashRoute = ResultsHashRouteImport.update({
  id: '/results/$hash',
  path: '/results/$hash',
  getParentRoute: () => rootRouteImport,
} as any)
const AvailabilityHashRoute = AvailabilityHashRouteImport.update({
  id: '/availability/$hash',
  path: '/availability/$hash',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/availability/$hash': typeof AvailabilityHashRoute
  '/results/$hash': typeof ResultsHashRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/availability/$hash': typeof AvailabilityHashRoute
  '/results/$hash': typeof ResultsHashRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/availability/$hash': typeof AvailabilityHashRoute
  '/results/$hash': typeof ResultsHashRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/availability/$hash' | '/results/$hash'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/availability/$hash' | '/results/$hash'
  id: '__root__' | '/' | '/availability/$hash' | '/results/$hash'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AvailabilityHashRoute: typeof AvailabilityHashRoute
  ResultsHashRoute: typeof ResultsHashRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results/$hash': {
      id: '/results/$hash'
      path: '/results/$hash'
      fullPath: '/results/$hash'
      preLoaderRoute: typeof ResultsHashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/availability/$hash': {
      id: '/availability/$hash'
      path: '/availability/$hash'
      fullPath: '/availability/$hash'
      preLoaderRoute: typeof AvailabilityHashRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AvailabilityHashRoute: AvailabilityHashRoute,
  ResultsHashRoute: ResultsHashRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
